### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-SircFerrer#1]
Buen trabajo @SircFerrer !

### Algunas pistas para acabarlo:

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Ordena los ficheros en carpetas.

### Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by SircFerrer** [comment]
Ya he subido lo que faltaba para acabarlo. Las 3 recomendaciones las acabaré al finalizar el curso. Gracias
